server:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    certfile: cert.pem
    keyfile: key.pem
  secret_key: tesla59
  allowed_origins:
    - http://localhost:3000

db:
  host: localhost
  port: 5432
  user: tesla
  password: tesla123
  dbname: cadet
  sslmode: disable
  timezone: Asia/Kolkata

environment: development
